spring.application.name=nexushr

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/nexushr
spring.datasource.username=postgres
spring.datasource.password=Soumya@12345

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=8080

# JWT
jwt.secret=MySuperSecretKeyForJWTAuthentication123456
jwt.expiration=86400000

# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379